subscribers:

  camera_reading:
    topic: /camera/depth/image_raw
    queue_size: 1

  pointcloud_reading:
    topic1: /robot1/stereo/points2
    topic2: /robot2/stereo/points2
    topic3: /robot3/stereo/points2
    topic4: /robot4/stereo/points2
    queue_size: 1

actions:

  camera_reading:
    name: /darknet_ros/check_for_objects

publishers:

  object_detector:
    topic: /darknet_ros/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /darknet_ros/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /darknet_ros/detection_image
    queue_size: 1
    latch: false

  pointcloud_image:
    topic: /darknet_ros/pointcloud_detection_image
    queue_size: 1
    latch: false

  compiled_message:
    topic: /detection/compiled_ros_msg
    queue_size: 1000
    latch: false

image_view:

  enable_opencv: true
  use_darknet: false
  wait_key_delay: 2
  enable_console_output: false
